nelmio_cors:
  defaults:
    allow_origin: ['*'] # Vous pouvez spécifier votre frontend ici
    allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
    allow_headers: ['Content-Type', 'Authorization']
    expose_headers: ['Content-Type', 'Authorization']
    max_age: 3600
    hosts: []
    origin_regex: false
  paths:
    '^/api/':
      allow_origin: ['http://localhost:3000'] # Origine autorisée
      allow_methods: ['GET', 'POST', 'OPTIONS']
      allow_headers: ['Content-Type', 'Authorization']
      expose_headers: ['Content-Type', 'Authorization']
      max_age: 3600
